### PR TITLE
chore: add commit lint workflow and add some nodejs configuration

### PR DESCRIPTION
**Pull request by RobyCigar**

### CODE REVIEW

**Comment by algonacci** [comment]
Hii @RobyCigar, can you explain about your commits and PR?

Is this to help the commit message or help the git flow? Because it have conflicts in it. 😅

**Comment by NurfitraPujo** [comment]
Kayaknya ini nambahain konfigurasi husky buat otomatis ngecek commit messagenya udah sesuai conventional commit belum. Dia diceknya setiap mau commit

**Review by algonacci — APPROVED** [review]
Approved, saya merge ya

**Comment by RobyCigar** [comment]
Ah sorry @algonacci I forgot to attach some description on the PR, as @NurfitraPujo said, husky + commit lint is to check the commit message whether it is conventional or not, if it's not conventional commit husky will automatically reject the commit.

And about the .nvmrc, this file can automatically switch contributor's nodejs & npm version if someone is using nvm 
https://stackoverflow.com/questions/23556330/run-nvm-use-automatically-every-time-theres-a-nvmrc-file-on-the-directory

**Pull request merged**
